### ISSUE TITLE
Does the Extension calculate the shipping cost via DHL API?

### ISSUE THREAD

**Issue by amenk** [netresearch/dhl-module-versenden-m1#2]
It might be a stupid question, but does the extension fetch the shipping costs on per kg base from the DHL API for the different destination countries? Source is Germany.

**Comment by mam08ixo** [comment]
There is no _Products and Rates API_ for DHL Business Customer Shipping. The module allows to use any installed (offline) shipping method for rates calculation (e.g. flatrate or table rates).

**Comment by amenk** [comment]
Thanks for the quick response

**Comment by ngolatka** [comment]
A general FYI: because this is a question we commonly see in support, we have an article about this in our Knowledge Base: https://dhl.support.netresearch.de/support/solutions/articles/12000023244
