### ISSUE TITLE
Problem with international postal codes

### ISSUE THREAD

**Issue by theroch** [netresearch/dhl-module-versenden-m1#3]
We have a customer with an international postal code 2032PM in the netherlands.

If we want to create a shipping info label, the process can not complete, because the ajax request returns with an http 500 error.
First problem:  The error is not visible for the user.

Second problem: The dhl error log says:
`Could not load DHL checkout shipping services: invalid value for "recipientZip" when calling CheckoutApi.checkoutRecipientZipAvailableServicesGet, must conform to the pattern /^[0-9]{5}$/.`

The regex pattern is only for german postal codes valid and not for international ones.
The first error is related to the magento module.
The second one is related to the DHL API.

**Comment by mam08ixo** [comment]
This error should not appear for NL addresses. Can you confirm the order's shipping address has the correct country code set?

**Comment by theroch** [comment]
Seems a temporary problem with the api. I'cant reproduce the issue now.

But you should check the error handling of the label creation form to inform the customer about errors.

**Comment by mam08ixo** [comment]
The HTTP 500 error and the log entry are unrelated. The log entry is not a web service error, postal code is validated in the application before sending the request to the parcel management API.

Label errors are displayed at the top of the packaging popup unless something crashes entirely. If you find the actual reason for the 500 server error, feel free to reopen this issue.
