### ISSUE TITLE
Uncaught ReferenceError: DhlServiceContainer is not defined

### ISSUE THREAD

**Issue by biswajit-unified** [netresearch/dhl-module-versenden-m1#4]
Hi,

We are getting this javascript error on the checkout page when a logged-in user enters the address.

![DeepinScreenshot_select-area_20210422031405](https://user-images.githubusercontent.com/58461485/115624880-def3e300-a318-11eb-99ff-5baa18d4f386.png)

![DeepinScreenshot_select-area_20210422031852](https://user-images.githubusercontent.com/58461485/115625299-7d804400-a319-11eb-81b2-dd9215cebe52.png)

This happens when we set the "Automatic Parcel Announcement" value to "Enable" or "Enable on Customers service" in the admin panel shipping methods section. The error disappears when we set the value to "Disable."

Please help.

**Comment by mam08ixo** [comment]
There is no support for custom/3rd party checkouts. You better not activate any value-added services.

**Comment by biswajit-unified** [comment]
Thanks for the update.
