### ISSUE TITLE
Visual-check-of-age remark not added to labels when generated via mass-action

### ISSUE THREAD

**Issue by berwa** [netresearch/dhl-module-versenden-m1#5]
Hello Netresearch-team,
today we discovered a problem in one of our customers' projects: the visual-check-of-age (e.g. 18 years) seems not be added properly if the DHL-labels are created via Magento mass-action from the order-grid.

**Preconditions**
- Module-version: 1.9.0
- Magento-version: Enterprise 1.14.3.1
- Sandbox Mode: Yes

**Steps to reproduce**
- Enable visual-check-of-age A18 in autogeneration-settings _(Shipping methods > DHL Versenden >  Shipment Defaults)_, save the dialogue, clear the cache
- Go to order-grid, select an order via its checkbox, use mass-actions _Create Shipment Labels_ and _Print Shipping Labels_ to generate and download the label

*Expected behavior*
- The downloaded label contains a remark "Alterssichtprüfung +18 !" (like it does when generated via the order's details)

*Actual behavior*
- The downloaded label does not contain any remark

Thank you and best regards

**Comment by mam08ixo** [comment]
Thank you for reporting the issue. I can confirm that the service value does not get properly set in the web service request.

**Comment by mam08ixo** [comment]
The issue was fixed in [version 1.9.2](https://github.com/netresearch/dhl-module-versenden-m1/releases/tag/1.9.2)

**Comment by berwa** [comment]
@mam08ixo thank you very much
