### ISSUE TITLE
Customs options to german receptions 

### ISSUE THREAD

**Issue by aterjung** [netresearch/dhl-module-versenden-m1#6]
Hi,

Commit ead60b4965359a7055ae4b9d80b6dd9849658314 introduces wrong results if the recipent as a ZIP code like 38xxxx. A Customs form is added for inner germany delivery what is obvious wrong.

In the method isCollectCustomsData, zip code is filterd with some regex rules, but the corresponding country is not checked.

**Comment by mam08ixo** [comment]
Oh no! Issue confirmed, fix coming soon. Thank you for the report.

**Comment by mam08ixo** [comment]
Fixed in [version 1.10.1](https://github.com/netresearch/dhl-module-versenden-m1/releases/tag/1.10.1)

**Comment by aterjung** [comment]
Thank you for your fast response!
