### ISSUE TITLE
Warenpost International

### ISSUE THREAD

**Issue by tim-breitenstein-it** [netresearch/dhl-module-versenden-m1#7]
Is the integration of `Warenpost International` planned?

[WARENPOST INTERNATIONAL Kundenpräsentation.pdf](https://github.com/netresearch/dhl-module-versenden-m1/files/8095537/WARENPOST.INTERNATIONAL.Kundenprasentation.pdf)

**Comment by mam08ixo** [comment]
_Warenpost International_ is supported since [v1.11.0](https://github.com/netresearch/dhl-module-versenden-m1/releases/tag/1.11.0).
