### ISSUE TITLE
End of life for SOAP API v2 and v3

### ISSUE THREAD

**Issue by borriglione** [netresearch/dhl-module-versenden-m1#9]
DHL is stopping 
- SOAP API v2 Support: 31. Mai 2025
- SOAP API v3 Support: 31.05.2026

1. I'm afraid that the module is using SOAP v2. Can you confirm that?
See: Ref: https://github.com/netresearch/dhl-module-versenden-m1/blob/master/src/lib/Dhl/Versenden/Bcs/Soap/GVAPI_2_0_de.php

2. Is it planned to publish a module update for SOAP v3 support or better REST webservice?

Anyway greetings to my old coworkers from Netresearch :wave: @mam08ixo and @Sebastian80 

> Sehr geehrte Nutzer der Geschäftskundenversand SOAP APIs,  Sehr geehrte Kund:innen und Geschäftspartner:innen,
> 
> DHL hat beschlossen, die Funktionalitäten der Geschäftskundenversand (GKV) SOAP API in die neue DHL Paket DE Versenden REST API zu überführen, um unseren Kunden eine zukunftsfähige und konveniente API-Schnittstelle zu bieten.
> 
> Aus diesem Grund wird die bereits veraltete Version 2 der Geschäftskundenversand SOAP API zum 31. Mai 2025 abgeschaltet. Die Version 3 der Geschäftskundenversand SOAP API soll ein Jahr später am 31.05.2026 ebenfalls abgeschaltet werden.
Neukundenregistrierungen für diese Versionen sind bereits jetzt schon nicht mehr möglich. 
> 
>  Sollten Sie eine Softwarelösung zur Beauftragung von Sendungen wie z.B. JTL, Centiro Solutions, Xentral ERP, etc. nutzen, setzen Sie sich bitte unverzüglich mit dem Hersteller in Verbindung, um noch rechtzeitig vor dem Abschalttermin Ende Mai 2025 auf eine neue Version zu wechseln.
> 
>   Sollten Sie die API direkt an Ihr System angebunden haben, stellen Sie bitte möglichst zeitnah die veraltete Version 2 Geschäftskundenversand SOAP API auf die neue DHL Paket DE Versenden REST API um; die Funktionalitäten der alten Geschäftskundenversand (GKV) SOAP API wurden vollständig in die neue DHL Paket DE Versenden REST API überführt.
> 
> Diese ist unter [DHL Paket DE Versenden REST API](https://developer.dhl.com/api-reference/parcel-de-shipping-post-parcel-germany-v2#get-started-section) im DHL API Developer Portal verfügbar. Hier finden Sie auch weitere hilfreiche Informationen für Ihren Umstieg.

**Comment by powli** [comment]
Hey @borriglione,

the module is already using v3 [sneakily](https://github.com/netresearch/dhl-module-versenden-m1/blob/master/src/lib/Dhl/Versenden/Bcs/Soap/GVAPI_2_0_de.php#L72
) since [1.6.0](https://github.com/netresearch/dhl-module-versenden-m1/releases/tag/1.6.0).

There are no plans to upgrade to the new REST service yet.

**Comment by borriglione** [comment]
Thanks @powli , greetings to you too of course :)
